services: 
  user_redis:
    image: redis:latest
    container_name: user_redis
    ports:
      - "6379:6379"  # Exposes Redis on the default port
    volumes:
      - user_data:/data  # Persists data in a named volume
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
    networks:
      - web  # Separate network for database communication

  booking_redis:
    image: redis:latest
    container_name: booking_redis
    ports:
      - "6380:6379"  # Exposes Redis on the default port
    volumes:
      - booking_data:/data  # Persists data in a named volume
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
    networks:
      - web  # Separate network for database communication
  
  inventory_redis:
    image: redis:latest
    container_name: inventory_redis
    ports:
      - "6381:6379"  # Exposes Redis on the default port
    volumes:
      - inventory_data:/data  # Persists data in a named volume
    environment:
      - REDIS_REPLICATION_MODE=master
    restart: unless-stopped
    networks:
      - web  # Separate network for database communication

networks:
  web:
    driver: bridge

volumes:
  user_data:
  booking_data:
  inventory_data: