services:
  app:
    build: .
    container_name: my_flask_app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.myapp.rule=Host(`www.chudars.lv`)"
      - "traefik.http.services.myapp.loadbalancer.server.port=5000"  # Port your app is exposed on
    networks:
      - web

  traefik:
    image: traefik:v3.2
    container_name: traefik
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"   # Redirects HTTP traffic
      - "8080:8080"  # Traefik dashboard
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - web

networks:
  web:
    driver: bridge